// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// glm_fit_cpp
Rcpp::List glm_fit_cpp(const Eigen::MatrixXd& X, const Eigen::VectorXd& y, std::string family, Rcpp::Nullable<Rcpp::NumericVector> weights, Rcpp::Nullable<Rcpp::NumericVector> offset, int maxit, double epsilon, double qr_tol);
RcppExport SEXP _fastmed_glm_fit_cpp(SEXP XSEXP, SEXP ySEXP, SEXP familySEXP, SEXP weightsSEXP, SEXP offsetSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP qr_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type qr_tol(qr_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(glm_fit_cpp(X, y, family, weights, offset, maxit, epsilon, qr_tol));
    return rcpp_result_gen;
END_RCPP
}
// mediation_analysis_cpp
void mediation_analysis_cpp(NumericMatrix data, CharacterVector column_names, DataFrame combinations, int nrep, std::string output_file, std::string pert, uint64_t base_seed, bool append);
RcppExport SEXP _fastmed_mediation_analysis_cpp(SEXP dataSEXP, SEXP column_namesSEXP, SEXP combinationsSEXP, SEXP nrepSEXP, SEXP output_fileSEXP, SEXP pertSEXP, SEXP base_seedSEXP, SEXP appendSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type column_names(column_namesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type combinations(combinationsSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type pert(pertSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type base_seed(base_seedSEXP);
    Rcpp::traits::input_parameter< bool >::type append(appendSEXP);
    mediation_analysis_cpp(data, column_names, combinations, nrep, output_file, pert, base_seed, append);
    return R_NilValue;
END_RCPP
}
// fastmed_test_p_value_cpp
double fastmed_test_p_value_cpp(NumericVector samples);
RcppExport SEXP _fastmed_fastmed_test_p_value_cpp(SEXP samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type samples(samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmed_test_p_value_cpp(samples));
    return rcpp_result_gen;
END_RCPP
}
// fastmed_test_calculate_statistics_cpp
List fastmed_test_calculate_statistics_cpp(NumericVector samples);
RcppExport SEXP _fastmed_fastmed_test_calculate_statistics_cpp(SEXP samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type samples(samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmed_test_calculate_statistics_cpp(samples));
    return rcpp_result_gen;
END_RCPP
}
// fastmed_test_two_bootstrap_samples
IntegerMatrix fastmed_test_two_bootstrap_samples(int n, uint64_t base_seed, uint64_t global_combination_idx, uint64_t rep_idx);
RcppExport SEXP _fastmed_fastmed_test_two_bootstrap_samples(SEXP nSEXP, SEXP base_seedSEXP, SEXP global_combination_idxSEXP, SEXP rep_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type base_seed(base_seedSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type global_combination_idx(global_combination_idxSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type rep_idx(rep_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmed_test_two_bootstrap_samples(n, base_seed, global_combination_idx, rep_idx));
    return rcpp_result_gen;
END_RCPP
}
// fastmed_test_ols_sigmas_cpp
List fastmed_test_ols_sigmas_cpp(NumericVector exposure, NumericVector mediator, NumericVector outcome);
RcppExport SEXP _fastmed_fastmed_test_ols_sigmas_cpp(SEXP exposureSEXP, SEXP mediatorSEXP, SEXP outcomeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type exposure(exposureSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mediator(mediatorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outcome(outcomeSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmed_test_ols_sigmas_cpp(exposure, mediator, outcome));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastmed_glm_fit_cpp", (DL_FUNC) &_fastmed_glm_fit_cpp, 8},
    {"_fastmed_mediation_analysis_cpp", (DL_FUNC) &_fastmed_mediation_analysis_cpp, 8},
    {"_fastmed_fastmed_test_p_value_cpp", (DL_FUNC) &_fastmed_fastmed_test_p_value_cpp, 1},
    {"_fastmed_fastmed_test_calculate_statistics_cpp", (DL_FUNC) &_fastmed_fastmed_test_calculate_statistics_cpp, 1},
    {"_fastmed_fastmed_test_two_bootstrap_samples", (DL_FUNC) &_fastmed_fastmed_test_two_bootstrap_samples, 4},
    {"_fastmed_fastmed_test_ols_sigmas_cpp", (DL_FUNC) &_fastmed_fastmed_test_ols_sigmas_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastmed(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
