# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastmed_test_p_value_cpp <- function(samples) {
    .Call(`_fastmed_fastmed_test_p_value_cpp`, samples)
}

fastmed_test_calculate_statistics_cpp <- function(samples) {
    .Call(`_fastmed_fastmed_test_calculate_statistics_cpp`, samples)
}

fastmed_test_two_bootstrap_samples <- function(n, base_seed, global_combination_idx, rep_idx) {
    .Call(`_fastmed_fastmed_test_two_bootstrap_samples`, n, base_seed, global_combination_idx, rep_idx)
}

fastmed_test_ols_sigmas_cpp <- function(exposure, mediator, outcome) {
    .Call(`_fastmed_fastmed_test_ols_sigmas_cpp`, exposure, mediator, outcome)
}

glm_fit_cpp <- function(X, y, family = "auto", weights = NULL, offset = NULL, maxit = 25L, epsilon = 1e-8, qr_tol = 1e-12) {
    .Call(`_fastmed_glm_fit_cpp`, X, y, family, weights, offset, maxit, epsilon, qr_tol)
}

mediation_analysis_cpp <- function(data, column_names, exposure_col_idx, mediator_col_idx, outcome_col_idx, nrep, output_file, weights = NULL, pert = "asymptotic", base_seed = 0L, mediator_family = "auto", outcome_family = "auto", replace_outcome = FALSE, output_format = "mediate", treat_value = 1.0, control_value = 0.0, chunk_size = 1024L, grain_size = 1L, overwrite = TRUE, excel_safe_csv = FALSE) {
    invisible(.Call(`_fastmed_mediation_analysis_cpp`, data, column_names, exposure_col_idx, mediator_col_idx, outcome_col_idx, nrep, output_file, weights, pert, base_seed, mediator_family, outcome_family, replace_outcome, output_format, treat_value, control_value, chunk_size, grain_size, overwrite, excel_safe_csv))
}
